### ISSUE TITLE
Formatting and colors in code snippets

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#10]
Currently, our code snippets appear like this. The background color and code formatting go well for legibility.

<img width="765" alt="Screenshot 2022-09-19 at 5 38 00 PM" src="https://user-images.githubusercontent.com/83692067/191013653-956534fc-dcfe-4fb7-97ad-e0c5d7198a84.png">

In the new website, the code snippets don't look well because the `bash` formatting is not there. For example, the comments in the code should be of lighter color.

<img width="722" alt="Screenshot 2022-09-19 at 5 38 28 PM" src="https://user-images.githubusercontent.com/83692067/191013738-43acc9c5-f151-4230-bf28-13779ba3da10.png">

**Comment by ankit01-oss** [comment]
Thanks @palashgdev

**Comment by palashgdev** [comment]
wrapped via https://mdxjs.com/guides/syntax-highlighting/
