### ISSUE TITLE
Table of contents running out of border in docs

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#102]
Nested items are running out of the border. We can replicate the same behaviour as our current website: https://signoz.io/docs/

<img width="333" alt="Screenshot 2022-10-28 at 11 07 56 AM" src="https://user-images.githubusercontent.com/83692067/198511099-ad71c3b9-d62c-45fc-a1e0-04e9273ac4ca.png">

**Comment by palashgdev** [comment]
fixed
