### ISSUE TITLE
Functionality to import shared components

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#104]
This one is critical as many pages in docs use this. A working example can be checked from here: https://raw.githubusercontent.com/SigNoz/signoz.io/main/docs/install/docker-standalone.md

Notice the `import` statements.

**Comment by ankit01-oss** [comment]
We need to shift all the components in the `/docs/shared/` folder: https://github.com/SigNoz/signoz.io/tree/main/docs/shared

**Comment by palashgdev** [comment]
Made a reference in `data/docs/faqs.mdx`
