### ISSUE TITLE
In-line text highlighting

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#11]
We use `this` format for higlighting some texts. In the below snapshot, notice how `otlp_spans` are highlighted.

<img width="614" alt="Screenshot 2022-09-19 at 5 41 26 PM" src="https://user-images.githubusercontent.com/83692067/191014218-ce76bc8f-a194-4f6d-a816-da6645e07912.png">

In the new website, the above format is causing the text to appear in a new line.

<img width="684" alt="Screenshot 2022-09-19 at 5 46 13 PM" src="https://user-images.githubusercontent.com/83692067/191014987-cff3aacc-b8c5-42b0-b6f0-b64c3cf8db93.png">

**Comment by ankit01-oss** [comment]
@palashgdev use the file I shared in slack for the same.

**Comment by palashgdev** [comment]
fixed
