### ISSUE TITLE
Linking internal pages

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#114]
Will this type of linking work?

<img width="841" alt="Screenshot 2022-10-28 at 4 52 39 PM" src="https://user-images.githubusercontent.com/83692067/198575728-69341b32-1786-43ab-92e7-00b31b269ef5.png">

Currently, I am using the entire link like shown below. The below opens in a new page. I think for docs section opening in the same tab makes more sense just like our current behaviour.
<img width="942" alt="Screenshot 2022-10-28 at 4 54 12 PM" src="https://user-images.githubusercontent.com/83692067/198575916-e64924b6-ab07-47b2-94f0-8770e717e90c.png">

**Comment by palashgdev** [comment]
yeah it will work until the structure is not finalised from product end can't comment over this one

**Comment by palashgdev** [comment]
same as https://github.com/SigNoz/signoz-website/issues/116

**Comment by ankit01-oss** [comment]
@palashgdev finalised as in we launch the new website, right?

**Comment by palashgdev** [comment]
@ankit01-oss can you try updating the docs links i think it should work and link internal pages

**Comment by ankit01-oss** [comment]
@palashgdev it's working. But links are not having the hyperlink color of SigNoz: https://signoz-website.vercel.app/docs/instrumentation/

We can close this issue. Have made a new one for hyperlink colors: https://github.com/SigNoz/signoz-website/issues/151
