### ISSUE TITLE
Clicks keep items highlighted even after other item is clicked

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#115]
Only the current item clicked should be highlighted.

<img width="247" alt="Screenshot 2022-10-28 at 6 01 38 PM" src="https://user-images.githubusercontent.com/83692067/198587365-9ef97d50-70b5-4799-93f9-117fe4a99db3.png">

**Comment by palashgdev** [comment]
😓

**Comment by palashgdev** [comment]
ok @ankit01-oss updating

**Comment by palashgdev** [comment]
@ankit01-oss from next time let's have a list of expectation

**Comment by palashgdev** [comment]
fixed
