### ISSUE TITLE
Style and format of tables

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#117]
Currently a table is looking like this. We can replicate the one from our current website as seen on this page: 
https://signoz.io/docs/instrumentation/troubleshoot-instrumentation/

<img width="888" alt="Screenshot 2022-10-29 at 5 08 10 PM" src="https://user-images.githubusercontent.com/83692067/198829303-b057a41b-d0b5-4a85-a20d-19641c2c070d.png">

**Comment by ankit01-oss** [comment]
@palashgdev You can check the live version here: https://signoz-website.vercel.app/docs/instrumentation_app/troubleshoot-instrumentation/

**Comment by palashgdev** [comment]
need design for same

**Comment by palashgdev** [comment]
this is the custom table we can add className to beautify those table so closing this one
