### ISSUE TITLE
Unsupported markdowns

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#119]
I am not sure how critical these markdowns are, but many markdowns are not supported in `.mdx`. @prashant-shahi can you provide some info regarding how important is it to have  a particular markdown. For example, <APITable> is not supported.

<img width="844" alt="Screenshot 2022-10-29 at 7 51 54 PM" src="https://user-images.githubusercontent.com/83692067/198836702-dd27f0a6-2556-4897-b97d-67760e81468e.png">

**Comment by ankit01-oss** [comment]
My bad. This is just a normal table it seems.

**Comment by palashgdev** [comment]
@ankit01-oss need design for this one

**Comment by palashgdev** [comment]
updated @ankit01-oss
