### ISSUE TITLE
Tags and ToC should start with the para after the cover photo

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#13]
Share this article, tags and table of contents should start from the first para after cover image.

<img width="632" alt="Screenshot 2022-09-19 at 6 18 50 PM" src="https://user-images.githubusercontent.com/83692067/191020975-2ac58e55-8ab2-481d-bfb6-ebfcc347cc49.png">

**Comment by ankit01-oss** [comment]
Yeah after cover image would be good @palashgdev . Currently it is coming beside the cover image.

<img width="1246" alt="Screenshot 2022-09-21 at 6 32 38 PM" src="https://user-images.githubusercontent.com/83692067/191510828-05234700-1dee-43f1-b076-5c2399e46f73.png">

**Comment by palashgdev** [comment]
@ankit01-oss if you see the mobile design cover photo is starting first

**Comment by palashgdev** [comment]
updated @ankit01-oss
