### ISSUE TITLE
Increase the size of headings in docs

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#145]
Can we increase the size of headings in docs?

Also currently h1, h2, h3 is very close, and not easily differentiable with naked eyes.

**Comment by palashgdev** [comment]
@ankit01-oss i need exact size for this one for mobile and desktop

**Comment by ankit01-oss** [comment]
Ok @palashgdev let me get back

**Comment by palashgdev** [comment]
all we need to update the number here 
```
src/components/MDX/components/Heading/config.ts
```

**Comment by ankit01-oss** [comment]
Done.
