### ISSUE TITLE
Cover Image not fitting

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#15]
How do we solve this @palashgdev ? Changing cover pics of all images in the existing blogs would be too time consuming, so we need to have the current ones fit in the new website.

<img width="692" alt="Screenshot 2022-10-06 at 8 25 58 PM" src="https://user-images.githubusercontent.com/83692067/194346551-e80f8451-855a-485e-8a11-c8b1388e2a72.png">

**Comment by palashgdev** [comment]
Fixed
