### ISSUE TITLE
Default Spacing between paragraphs

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#17]
I have used br tags to create spacing between paragraphs. Need to make it default, where the mdx file takes in spacing when a paragraph is changed.

<img width="653" alt="Screenshot 2022-10-06 at 8 34 29 PM" src="https://user-images.githubusercontent.com/83692067/194348606-fd5a5c44-cadc-4091-ae5d-8ab55b998246.png">

**Comment by palashgdev** [comment]
Fixed
