### ISSUE TITLE
Sentences under bullet points have color #000000 instead of #404C5E

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#18]
Texts in bullet points need to have the same color as the main content body

<img width="795" alt="Screenshot 2022-10-06 at 8 35 58 PM" src="https://user-images.githubusercontent.com/83692067/194348909-aa6956b0-034c-4b01-a1bd-1edfd42b77d0.png">

**Comment by palashgdev** [comment]
Fixed
