### ISSUE TITLE
Code snippet not working

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#20]
This particular code snippet is not working

<img width="590" alt="Screenshot 2022-10-06 at 8 50 32 PM" src="https://user-images.githubusercontent.com/83692067/194352522-d1d94716-4e4f-4742-b109-cfe64bb379be.png">

Rather than coming as a code block, it is getting highlighted in different lines.

<img width="732" alt="Screenshot 2022-10-06 at 8 51 34 PM" src="https://user-images.githubusercontent.com/83692067/194352749-8d537fc4-67c0-428e-8bbf-bbee44b3542f.png">

But the code snippets are working. Not sure where I am going wrong. I will share the blog content with you to verify.

**Comment by palashgdev** [comment]
Fixed
