### ISSUE TITLE
Change the color of hyperlinks to #F25733

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#21]
Currently the hyperlinks have the same color as texts, so no visible cue to if they are links or normal text.

<img width="177" alt="Screenshot 2022-10-06 at 8 53 03 PM" src="https://user-images.githubusercontent.com/83692067/194353182-1ab2a06d-dae9-4ccd-aec2-6f73b97dc915.png">

**Comment by palashgdev** [comment]
fixed
