### ISSUE TITLE
How to create clickable images which can lead to another page

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#22]
Currently we use the following code:

<img width="783" alt="Screenshot 2022-10-06 at 8 54 07 PM" src="https://user-images.githubusercontent.com/83692067/194353511-f970db96-5479-453d-97bd-b5bf483d8f58.png">

[![Deployment Docs](/img/blog/common/deploy_docker_documentation.webp)](https://signoz.io/docs/install/docker/?utm_source=blog&utm_medium=opentelemetry_colllector)

**Comment by palashgdev** [comment]
```
<a target='_blank' href='https:google.com'>
<img src='https://images.unsplash.com/photo-1664575196412-ed801e8333a1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2942&q=80' alt='sample alt' />
</a>
```
