### ISSUE TITLE
`/` missing in the end in url 

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#40]
Not very sure how this will affect SEO, but we have come across issues where google recognizes these two links differently:
- `https://signoz.io/blog/community-update-17/`
- `https://signoz.io/blog/community-update-17`

Would be good to have the ending `/` in our URLs

<img width="634" alt="Screenshot 2022-10-12 at 5 27 40 PM" src="https://user-images.githubusercontent.com/83692067/195336630-ed257959-ac96-4748-869c-087fce2bb697.png">

**Comment by palashgdev** [comment]
Fixed
