### ISSUE TITLE
Bullet and numbering both appearing 

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#41]
Check under `List of reasons why to use OpenTelemetry Collector:`

<img width="878" alt="Screenshot 2022-10-12 at 5 35 09 PM" src="https://user-images.githubusercontent.com/83692067/195338046-23b5806b-0d81-486e-a0d8-fad70aba5669.png">

If you see point number 1, it has both bullet and 1 in it.

<img width="765" alt="Screenshot 2022-10-12 at 5 35 27 PM" src="https://user-images.githubusercontent.com/83692067/195338109-c24c8fe6-5993-466a-a8f3-cc6583bf3480.png">

**Comment by palashgdev** [comment]
Fixed
