### ISSUE TITLE
Can we change lists with `-` markdown to unordered list

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#42]
Currently the below markdown results in a numbered list. But can we change that to unnumbered list with bullet points.

<img width="715" alt="Screenshot 2022-10-12 at 5 40 09 PM" src="https://user-images.githubusercontent.com/83692067/195338952-c11670e5-b56c-4b62-b257-99494cec9490.png">

The above markdown should appear as follows:

- It provides a vendor-agnostic way to collect telemetry data.
- The Collector offloads responsibility from the application to manage telemetry data, thereby reducing overhead and providing separate concerns from the application for any telemetry configuration.
- Using OpenTelemetry Collector, you can export telemetry data in multiple formats to multiple observability vendors of your choice.
- It enables quick config-based updates to your telemetry data pipeline. It is trivial to update a config file to receive data in another format.
- It can also help collect host metrics such as RAM, CPU, and storage capacity.

**Comment by palashgdev** [comment]
Fixed
