### ISSUE TITLE
Code snippet not aligned with the main text body

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#43]
https://www.loom.com/share/2e4fa9801cde4a19a06c82b3a6ae19b9

**Comment by ankit01-oss** [comment]
seems like a recurring issue.

<img width="810" alt="Screenshot 2022-10-12 at 5 48 17 PM" src="https://user-images.githubusercontent.com/83692067/195340520-bf824dbb-79e4-406c-b5fc-723a008b500b.png">

**Comment by palashgdev** [comment]
Fixed
