### ISSUE TITLE
Change caption color to the main body text color

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#44]
Currently, the caption color is set to `#000000`

<img width="885" alt="Screenshot 2022-10-12 at 5 50 33 PM" src="https://user-images.githubusercontent.com/83692067/195341287-02baa5ca-f292-42d1-a554-2f8a4003cbf9.png">

**Comment by palashgdev** [comment]
then what's the expected color @ankit01-oss ?

**Comment by palashgdev** [comment]
Fixed this one
