### ISSUE TITLE
Share Icons Address In Detail Blog Page

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz-website#47]
<img width="376" alt="Screenshot 2022-10-13 at 12 32 48 AM" src="https://user-images.githubusercontent.com/88981777/195426544-89da5f93-9d97-40c9-9884-f5cd1d687305.png">

**Comment by ankit01-oss** [comment]
@palashgdev these icons should open up the respective social website, and open up a post with the link of the article.

Check the behaviour in this website: https://www.datadoghq.com/blog/opentelemetry-logs-datadog-exporter/

You will find the social icons at the end.

**Comment by palashgdev** [comment]
@ankit01-oss I want address not icons right now all are redirecting to facebook

**Comment by palashgdev** [comment]
fixed
