### ISSUE TITLE
Highlighting in Table of Contents

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#5]
In the table of Contents, only the heading which is currently being scrolled should be highlighted. Here we can see multiple headings highlighted.

<img width="979" alt="Screenshot 2022-09-19 at 3 41 06 PM" src="https://user-images.githubusercontent.com/83692067/190995596-8e68b247-75f4-42f2-8e1e-181ba4061e81.png">

**Comment by ankit01-oss** [comment]
Have added a blog in my local. Let me share that file on slack. @palashgdev

**Comment by palashgdev** [comment]
Fixed
