### ISSUE TITLE
Article is not clickable in the hero section of blog landing page

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#51]
Ideally the entire area should be clickable and should lead to the article, including the title, description, and author details.

<img width="1404" alt="Screenshot 2022-10-13 at 3 48 48 PM" src="https://user-images.githubusercontent.com/83692067/195571157-31fbbe78-a859-4597-9b8f-5c6397dca52b.png">

**Comment by palashgdev** [comment]
fixed
