### ISSUE TITLE
Title update for All Blog Landing Page

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#52]
Blog Landing page should show a title: `SigNoz Blog`

Currently it shows `https...`

<img width="271" alt="Screenshot 2022-10-13 at 4 12 54 PM" src="https://user-images.githubusercontent.com/83692067/195576290-d8a3ba98-9f8d-4aa0-9379-d13d65fe4107.png">

**Comment by palashgdev** [comment]
fixed
