### ISSUE TITLE
Author details seems hardcoded in the hero section

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#54]
This article has `Ankit Nayan` as the author, but it shows Chenna Raidu.

<img width="635" alt="Screenshot 2022-10-13 at 4 22 11 PM" src="https://user-images.githubusercontent.com/83692067/195577987-8ecd1598-07af-4fa6-b2a9-91240c406c1b.png">

**Comment by palashgdev** [comment]
fixed
