### ISSUE TITLE
Markdown giving unexpected line breaks.

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#58]
Markdown:

<img width="862" alt="Screenshot 2022-10-18 at 4 57 12 PM" src="https://user-images.githubusercontent.com/83692067/196417014-5d4eaeaf-ac6a-4fae-b172-7f28484bcb03.png">

Output:
<img width="762" alt="Screenshot 2022-10-18 at 4 57 37 PM" src="https://user-images.githubusercontent.com/83692067/196417095-f8f433a7-24a6-46c8-a445-09f8d9b5959f.png">

The line breaks after numbering are unnecessary.

**Comment by palashgdev** [comment]
fixed
