### ISSUE TITLE
Would be better to have Author name bigger than the occupation

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#6]
This was not in the design, but it would be better to have author name bigger than the `occupation`. Like, we currently have in our blog.
<img width="482" alt="Screenshot 2022-09-19 at 4 46 35 PM" src="https://user-images.githubusercontent.com/83692067/191005826-9b5df5e0-ec86-4d52-aefe-481825c28622.png">

<img width="414" alt="Screenshot 2022-09-19 at 4 46 12 PM" src="https://user-images.githubusercontent.com/83692067/191005775-45bebfbc-664c-4d77-a608-2c2fade8d5cc.png">

**Comment by ankit01-oss** [comment]
@palashgdev ok. Would be good to share in figma?

**Comment by palashgdev** [comment]
yes please @ankit01-oss

**Comment by palashgdev** [comment]
Fixed
