### ISSUE TITLE
Image does not expand when clicked

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#7]
Using the following to embed the image:

<figure data-zoomable align='center'>
    <img src="/img/blog/2022/09/opentelemetry_architecture.webp" alt="OpenTelemetry Architecture"/>
    <figcaption><i>Architecture - How OpenTelemetry fits in an application architecture. OTel collector refers to OpenTelemetry Collector</i></figcaption>
</figure>

Let me know if something else has to be used. The image is visible, but on clicking nothing happens. Ideally it should open up a zoomed version.

**Comment by ankit01-oss** [comment]
Ok. Can you share a reference @palashgdev ? Currently, I am using the below code snippet for images:

<img width="831" alt="Screenshot 2022-09-21 at 6 25 46 PM" src="https://user-images.githubusercontent.com/83692067/191509313-ea3826bd-3929-4add-9c5b-f9c8160d8f79.png">

Would be great if you can share the full component for uploading images in the new blog.

<br></br>

**Comment by palashgdev** [comment]
Updated
