### ISSUE TITLE
Change hyperlink colors of external links too

### ISSUE THREAD

**Issue by zriyansh** [SigNoz/signoz-website#76]
links to signoz blog are orange in color, externals links, although clickable, are black in color.

![Screenshot 2022-10-23 at 13 29 59](https://user-images.githubusercontent.com/52788043/197381150-cee965bc-03b5-4998-a767-da38088f68a6.png)

**Comment by ankit01-oss** [comment]
@zriyansh can you mention which blog this is? Would be easier to look into.

**Comment by palashgdev** [comment]
this is a custom component you can add className with `text-signoz-primary` this will work
