### ISSUE TITLE
More padding around blog cards on tag landing page

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#77]
The content is almost touching the boundary. We can have some good padding here like 64px, etc.

<img width="1440" alt="Screenshot 2022-10-25 at 12 32 30 PM" src="https://user-images.githubusercontent.com/83692067/197704734-6e161fc2-ba2a-4281-8b55-db2561c63ac4.png">

**Comment by palashgdev** [comment]
Fixed

**Comment by palashgdev** [comment]
fixed
