### ISSUE TITLE
Change the title of homepage to `Open source APM | SigNoz`

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#79]
Currently I see a URL in the browser for our homepage. 
<img width="168" alt="Screenshot 2022-10-25 at 7 16 17 PM" src="https://user-images.githubusercontent.com/83692067/197790429-7a8f10ac-158f-4205-82d2-1d3da617950c.png">

It should be updated to:

`Open source APM | SigNoz`

**Comment by palashgdev** [comment]
fixed
