### ISSUE TITLE
How to list Bullet Points

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#8]
How to list bullet points in the new website? Used to do as shown in the below snapshot.

<img width="910" alt="Screenshot 2022-09-19 at 5 17 18 PM" src="https://user-images.githubusercontent.com/83692067/191010487-a762c204-d2e3-4a5a-a973-9ed62e18f995.png">

Currently, the above snippet appears as follows. It is just highlighted differently. Note that the bullet points should appear under <li> tag for SEO purposes.

<img width="709" alt="Screenshot 2022-09-19 at 5 19 04 PM" src="https://user-images.githubusercontent.com/83692067/191010645-e7288d74-5367-4ec9-beb9-a686cbe84abf.png">

**Comment by ankit01-oss** [comment]
@palashgdev tried using the `ul` tag, but it is not reflecting in the blog.

<img width="658" alt="Screenshot 2022-09-21 at 6 29 14 PM" src="https://user-images.githubusercontent.com/83692067/191510257-dde02a7f-973b-4e5d-8296-2d8bc7ab07b6.png">


In the blog:

<img width="666" alt="Screenshot 2022-09-21 at 6 30 26 PM" src="https://user-images.githubusercontent.com/83692067/191510330-e8aab960-af17-4165-90c7-72eacd82b77c.png">

**Comment by palashgdev** [comment]
Although there is a global style provided by Tailwind that overrides the style.You can also change via the tailwind class but for now i have already solved this one.
