### ISSUE TITLE
Turn off Table of Contents for blogs with no Table of contents

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#83]
A blog which has no headings: https://signoz-website.vercel.app/blog/red-metrics-calculation/

For this blog, `In This Article` should be hidden.

If possible, we can also implement it as Docusaurus which has a feature to switch the ToC on or off by enabling the below inmeta description.

`hide_table_of_contents: true`

**Comment by palashgdev** [comment]
Fixed
