### ISSUE TITLE
A cross button to turn off the announcement bar

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#89]
[Figma Design Link](https://www.figma.com/file/gu9Dlot5tHJDHv4FqwCljN/SigNoz-Website-v2?node-id=1%3A110)

<img width="461" alt="Screenshot 2022-10-26 at 6 34 22 PM" src="https://user-images.githubusercontent.com/83692067/198033006-14baa022-6f6a-4a40-9bf4-2805b85b943a.png">

**Comment by palashgdev** [comment]
Fixed
