### ISSUE TITLE
Numbered list and line breaks

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#9]
Currently, the below snippet in `.mdx` file appears as shown in the second screenshot.

How it appears in `.mdx` file

<img width="806" alt="Screenshot 2022-09-19 at 5 35 19 PM" src="https://user-images.githubusercontent.com/83692067/191013227-ecb0b5fd-ca0e-4cb5-9a5a-c51eee7f2bdc.png">

How it appears in the new website
<img width="691" alt="Screenshot 2022-09-19 at 5 36 09 PM" src="https://user-images.githubusercontent.com/83692067/191013397-6404db41-4ba5-44c7-a8ae-bd6aeefaee55.png">

How it should appear:
<img width="764" alt="Screenshot 2022-09-19 at 5 37 13 PM" src="https://user-images.githubusercontent.com/83692067/191013543-8fb4bde6-120a-410c-862f-159f2a00cdd6.png">

**Comment by palashgdev** [comment]
@ankit01-oss is it resolved ?

**Comment by ankit01-oss** [comment]
Yes @palashgdev, will give more details in a new issue.
