### ISSUE TITLE
Tag Design Pointers

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#91]
1. Can we decrease the size of the text in tags, and the tag box too? Tag text should come in one line otherwise it looks weird:
From blog: https://signoz-website.vercel.app/blog/opentelemetry-kafka/

<img width="398" alt="Screenshot 2022-10-26 at 6 46 34 PM" src="https://user-images.githubusercontent.com/83692067/198035638-ba102d91-9001-4254-a222-263fc44b76f3.png">

**Comment by palashgdev** [comment]
added the ellipses when length exceed 200px is there any more exceptions ?

**Comment by palashgdev** [comment]
please feel free to re open is there is any other expection
