### ISSUE TITLE
Redundant data in blogs with two authors

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#92]
Need to make `Date` and `Time to read` appear only once in blogs with two authors:

Blog: https://signoz-website.vercel.app/blog/opentelemetry-kafka/
<img width="718" alt="Screenshot 2022-10-26 at 6 47 55 PM" src="https://user-images.githubusercontent.com/83692067/198035980-2633a118-731d-4a7f-9303-194532100020.png">

On our current website: https://signoz.io/blog/opentelemetry-kafka/
<img width="799" alt="Screenshot 2022-10-26 at 6 52 22 PM" src="https://user-images.githubusercontent.com/83692067/198036996-94bdeed1-0c9a-40d4-8306-0ecf2b4ab3ad.png">

**Comment by palashgdev** [comment]
fixed
