### ISSUE TITLE
A single line break introducing too much space in docs

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz-website#93]
Output 👇
<img width="868" alt="Screenshot 2022-10-27 at 12 50 48 PM" src="https://user-images.githubusercontent.com/83692067/198217249-cfb713e9-27c5-4794-93cd-3fe881f9d98d.png">

Markdown 👇
<img width="726" alt="Screenshot 2022-10-27 at 12 51 43 PM" src="https://user-images.githubusercontent.com/83692067/198217272-077b07d4-531e-4350-bfb4-0389b0934550.png">

**Comment by palashgdev** [comment]
fixed
